version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.8  # Use any Docker image with Docker installed
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7  # Specify the Docker version
          docker_layer_caching: true

      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - run:
          name: Azure Login
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - run:
          name: ACR Login
          command: |
            az acr login --name $ACR_NAME

      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$CIRCLE_SHA1 ./Go-app/
            docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$CIRCLE_SHA1

      - run:
          name: Save the image tag
          command: |
            echo $CIRCLE_SHA1 > image_tag.txt
            
      - persist_to_workspace:
          root: .
          paths:
            - image_tag.txt

      - run:
          name: Logout from ACR
          command: |
            docker logout $ACR_NAME.azurecr.io

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
