apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deploy
  namespace: go-survey
  labels:
    app: goapp
spec:
  selector:
    matchLabels:
      app: goapp
  replicas: 2
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goapp
          image: cluster1devacr.azurecr.io/goapp:latest # Make sure to update the image name to match the build.sh script 
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-app-service.go-survey.svc:27017"
            - name: APP_PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: goapp
  namespace: go-survey
  labels:
    app: goapp
spec:
  selector:
    app: goapp
  type: LoadBalancer
  ports:
    - name: goapp
      port: 8080
      targetPort: 8080
