name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Secrets (Remove after testing)
        run: |
          echo "Client ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "Client Secret: ${{ secrets.AZURE_CLIENT_SECRET }}"
          echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID }}"

      - name: Login to Azure using Service Principal
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Run Azure CLI command
        run: az account show

      - name: Azure CLI - Log in to ACR
        run: |
          az acr login --name ${{ env.REGISTRY_NAME }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REPO_NAME }}:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.REPO_NAME }}:${{ github.sha }}

      - name: Logout from Docker
        run: |
          docker logout ${{ env.REGISTRY_NAME }}.azurecr.io
