name: Continuous Integration
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: cluster1devacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build, tag, and push image to Azure Container Registry
        env:
          ACR_LOGIN_SERVER: cluster1devacr.azurecr.io
          ACR_REPOSITORY: goapp
          IMAGE_TAG: latest
        run: |
          docker build -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$IMAGE_TAG ./Go-app/
          docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$IMAGE_TAG
