name: Continuous Integration
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: elgohr/acr-login-action@master
        with:
          service_principal: ${{ secrets.ACR_PRINCIPAL }}
          service_principal_password: ${{ secrets.ACR_PRINCIPAL_PASSWORD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ secrets.REGISTRY }}
          repository: ${{ secrets.REPOSITORY }}

      - name: Build, tag, and push image to Azure Container Registry
        env:
          registry: ${{ secrets.REGISTRY }}
          repository: ${{ secrets.REPOSITORY }}
          image_tag: latest
        run: |
          docker build -t $registry/$repository:$image_tag ./Go-app/
          docker push $registry/$repository:$image_tag
